// Code generated by Herebyfile.mjs generate:enums from tsc/pkg/core/compileroptions.go. DO NOT EDIT.

export enum ModuleDetectionKind {
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}
